version: '3.9'

services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"

  postgresql:
    container_name: postgresql
    build:
      context: .
      dockerfile: ./code/postgresql/Dockerfile
    volumes:
      - './code/postgresql:/var/lib/postgresql/data'
    env_file: .env
    ports:
      - '5432:5432'

  python:
    container_name: python
    build:
      context: .
      dockerfile: ./code/python/Dockerfile
    volumes:
      - './logs:/logs'
    depends_on:
      - postgresql
      - selenium
